Load Dataset

In [18]:
from sklearn import datasets
import numpy as np
import pandas as pd
breast_cancer = datasets.load_breast_cancer()
X = breast_cancer.data
Y = breast_cancer.target

In [19]:
print(X)
print(breast_cancer.feature_names)
print(X.shape)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
(569, 30)


Dataset preparation

In [20]:
# Dataset preparation
data_with_feature_name = pd.DataFrame(data = X, columns = breast_cancer.feature_names)
data = data_with_feature_name
data['class'] = Y

Train and Test Split

In [21]:
# Train and Test Split
from sklearn.model_selection import train_test_split
X_data = data.drop('class', axis=1)
Y_data = data['class']
X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_data, test_size=0.2, stratify = Y_data, random_state = 1)

Perceptron Class

In [22]:
from sklearn.metrics import accuracy_score
X_train = X_train.values
X_test = X_test.values

In [23]:
class Perceptron:

    def __init__(self):
        self.w = None
        self.b = None

    def model(self, x):

        return 1 if (np.dot(self.w, x) >= self.b) else 0

    def predict(self, X):
        y = []
        for x in X:
            y_pred = self.model(x)
            y.append(y_pred)
        return np.array(y)

    def fit(self, X, Y, epochs = 10, lr = 0.1):
        self.w = np.ones(X.shape[1])
        self.b = 0
        w_matrix = []
        accuracy = {}
        max_accuracy = 0

        for i in range(epochs):
            for x,y in zip(X, Y):
                y_train_pred = self.model(x)
                if y_train_pred == 1 and y == 0:
                    self.w = self.w - lr * x
                    self.b = self.b + lr * 1
                elif y_train_pred == 0 and y == 1:
                    self.w = self.w + lr * x
                    self.b = self.b - lr * 1
            w_matrix.append(self.w)
            accuracy[i] = accuracy_score(self.predict(X), Y)
            if (accuracy[i] > max_accuracy):
                max_accuracy = accuracy[i]
                check_point_w = self.w
                check_point_b = self.b

        self.w = check_point_w
        self.b = check_point_b

        print("Maximum training accuracy :",max_accuracy)
        return np.array(w_matrix)

In [24]:
perceptron = Perceptron()
weight_mtx = perceptron.fit(X_train, Y_train, 1000, 0.1)
y_pred_test = perceptron.predict(X_test)
print("Testing accuracy : ", accuracy_score(y_pred_test, Y_test))

Maximum training accuracy : 0.9098901098901099
Testing accuracy :  0.9298245614035088
